name: Build
on:
  push:
    branches: "*"
    tags-ignore: [ "*" ]
  pull_request:
  release:
    types: [ released ]
  workflow_dispatch:
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: "validate gradle wrapper"
        uses: gradle/actions/wrapper-validation@v4
      - name: "jdk"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/caches/VanillaGradle
            .gradle/loom-cache
            paper/.gradle/caches/paperweight
          key: ${{ runner.os }}-gradle1-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle1-
      - name: "make gradle wrapper executable"
        run: chmod +x ./gradlew
      - name: "build"
        run: ./gradlew build
      - name: "capture build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
